name: Azure Keyvault Secrets

on:
    workflow_dispatch: 

permissions: 
  id-token: write
  contents: read

jobs:
    Azure_Secrets_Fetch:
        runs-on: ubuntu-latest
        steps:          
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Azure Login
              uses: azure/login@v2
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

            - name: Azure CLI script
              uses: azure/cli@v2
              with:
                azcliversion: latest
                inlineScript: |
                  az account show
            - name: Fetch secrets from Azure Key Vault
              id: fetch-secrets
              uses: manojwalker/azvault-action@v1.0.16
              with:
                vault-name:  ${{ secrets.OUR_KV}}
              env:
                AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
                CLIENTSECRET: ${{ secrets.CLIENTSECRET }}
                AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
            - name: List all secret names and values (Not recommended for prod)
              uses: azure/cli@v1
              with:
                inlineScript: |
                  for secret in $(az keyvault secret list --vault-name "${{ secrets.OUR_KV}}" --query "[].name" -o tsv); do
                    echo "$secret: $(az keyvault secret show --vault-name "${{ secrets.OUR_KV}}" --name "$secret" --query value -o tsv)"
                  done