name: My First Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'
jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: action/checkout@v4 

        - name: Welcome Mesage
          run: echo "My first Github Action Job"

        - name: List files
          run: ls

        - name: Read file
          run: cat README.md
