name: My First Workflow

on: push

jobs: 
    first_job:
        runs-on: ubutnu-latest
        steps:
        - name: Welcome Mesage
          run: echo "My first Github Action Job"

        - name: List files
          run: ls

