name: My First Workflow

on: push

jobs: 
    first_job:
        runs-on: ubutnu
        steps:
        - name: Welcome Mesage
          run: echo "My first Github Action Job"

        - name: List files
          run: ls

        - name: Read file
          run: cat README.md