name: My First Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'
jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4 

        - name: Welcome Mesage
          run: | 
             echo "My first Github Action Job"
             ls -lart 
             cat README.md

        - name: Generate ASCII Artwork
          run: cowsay -f snake "Reun for cover I am a Actor VISHAL....RAWR"  >> snake.txt

