name: Generate ASCII network

on:
    push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
         - name: Checkout Repo
           uses: actions/checkout@v4
         
         - name: Install Cowsay Program
           run: sudo apt-get install cowsay -y
           
         - name: Execute Cowsay CMD
           run: cowsay -f snake "Reun for cover I am a Actor VISHAL....RAWR"  >> snake.txt

         - name: Test File Exists
           run: grep -i "snake" snake.txt
           
         - name: Read File
           run: cat snake.txt

         - name: List Repo Files
           run: ls -lart