name: Generate ASCII network

on:
    push

jobs:
    Build_job:
        runs-on: ubuntu-latest
        steps:
         - name: Install Cowsay Program
           run: sudo apt-get install cowsay -y
           
         - name: Execute Cowsay CMD
           run: cowsay -f dragon "Run for cover I am a AK Red Dragon....RAWR"  >> snake.txt

         - name: Sleep for 30 seconds
           run: sleep 10

    Test_job:
         needs: Build_job
         runs-on: ubuntu-latest
         steps:
           - name: Sleep for 30 seconds
             run: sleep 10

           - name: Test File Exists
             run: grep -i "dragon" snake.txt

    Deploy_job:
        needs: Test_job
        runs-on: ubuntu-latest
        steps:
          - name: Read File
            run: cat snake.txt

          - name: Deploy
            run: echo "Deploying.....""
          
