name: Generate ASCII network

on:
    push

env:
   USER_ID: ajro45
   USER_PWD: AJAYRO$%#@
   URL: aa1302.io   

jobs:
    Build_job:
        runs-on: ubuntu-latest
        steps:
         - name: Install Cowsay Program
           run: sudo apt-get install cowsay -y
           
         - name: Execute Cowsay CMD
           run: cowsay -f dragon "Run for cover I am a AK Red Dragon....RAWR"  >> snake.txt
        
         - name: Upload the File
           uses: actions/upload-artifact@v4
           with:
             name: Snake-text-File
             path: snake.txt
           
         - name: Loggin into the Website
           run: echo $USER_ID/$USER_PWD/env.URL

    Test_job:
         needs: Build_job
         runs-on: ubuntu-latest
         steps:
         - name: Download the File
           uses: actions/download-artifact@v4
           with:
             name: Snake-text-File

         - name: Test File Exists
           run: grep -i "dragon" snake.txt

         - name: Loggin into the Website
           run: echo $USER_ID/$USER_PWD/env.URL

    Deploy_job:
        needs: Test_job
        runs-on: ubuntu-latest
        steps:
         - name: Download the File
           uses: actions/download-artifact@v4
           with:
             name: Snake-text-File
         - name: Read File
           run: cat snake.txt
         - name: Loggin into the Website
           run: echo $USER_ID/$USER_PWD/env.URL

         - name: Deploy
           run: echo "Deploying....."
          
